project:
  type: website
website:
  title: "Peer Review 2"
  description: "Answers for peer-reviewing of the Parallel prac"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
    right:
      - text: "Practical 2"
        href: Practical2.qmd
